@startuml

class Event
Event : private Object source
Event : Object target
Event : Method callback
Event : String trigger
Event : long time

class EventLisenter
EventLisenter : Map<String,Event> events
EventLisenter : void addListener()
EventLisenter : void trigger()

class Mouse
Mouse : void focus()
Mouse : void click()
Mouse : void doubleClick()
Mouse : void ...()

class MouseEventCallback

interface MouseEventType

EventLisenter <|-- Mouse

note as n1
如果使用链表实现，
链栈不需要maxSize
end note


@enduml