
package com.panda.WSConsumer;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceDemoService", targetNamespace = "http://externalService.app.panda.com/", wsdlLocation = "http://localhost:9090/WebServiceDemo?wsdl")
public class WebServiceDemoService
    extends Service
{

    private final static URL WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDEMOSERVICE_EXCEPTION;
    private final static QName WEBSERVICEDEMOSERVICE_QNAME = new QName("http://externalService.app.panda.com/", "WebServiceDemoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/WebServiceDemo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDEMOSERVICE_WSDL_LOCATION = url;
        WEBSERVICEDEMOSERVICE_EXCEPTION = e;
    }

    public WebServiceDemoService() {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebServiceDemoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebServiceDemoService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME);
    }

    public WebServiceDemoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDEMOSERVICE_QNAME, features);
    }

    public WebServiceDemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDemoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceDemo
     */
    @WebEndpoint(name = "WebServiceDemoPort")
    public WebServiceDemo getWebServiceDemoPort() {
        return super.getPort(new QName("http://externalService.app.panda.com/", "WebServiceDemoPort"), WebServiceDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceDemo
     */
    @WebEndpoint(name = "WebServiceDemoPort")
    public WebServiceDemo getWebServiceDemoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://externalService.app.panda.com/", "WebServiceDemoPort"), WebServiceDemo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDEMOSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDEMOSERVICE_EXCEPTION;
        }
        return WEBSERVICEDEMOSERVICE_WSDL_LOCATION;
    }

}
